version: "2.4"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
  partner-service:
    image: clue/json-server
    ports:
      - "8090:80"
    volumes:
      - "./src/main/resources/db.json:/data/db.json"
  ticker-service:
    image: node:12-alpine
    ports:
      - "8091:8085"
    volumes:
      - "./src/test/resources/lag-nodejs-server.js:/app/lag-nodejs-server.js"
    command: ["node", "/app/lag-nodejs-server.js"]
