spring:
  application:
    name: Kotlin Playground
  main:
    banner-mode: off

partner-service:
  endpoint: http://localhost:8090
  post-path: ${partner-service.endpoint}/posts
  comment-path: ${partner-service.endpoint}/comments
ticket-service:
  endpoint: http://localhost:8091
